// SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package gitlab

const (
	pipelinePathOIDC   = ".gitlab/slsa-source.yml"
	pipelinePathCosign = ".gitlab/slsa-source.yml"
	cosignPubPath      = ".gitlab/cosign.pub"
	gitlabCIPath       = ".gitlab-ci.yml"

	pipelineCommitMessage = "Add SLSA Source Provenance Pipeline"

	pipelinePRBody = `This merge request adds automated SLSA source provenance generation to your GitLab repository.

## What This Does

- Generates SLSA source provenance attestations on every push to branches and tags
- Stores attestations in git notes for later verification
- Integrates with your existing GitLab CI/CD pipeline

## Files Added

- ` + "`" + `.gitlab/slsa-source.yml` + "`" + ` - SLSA source provenance job template
- Modified: ` + "`" + `.gitlab-ci.yml` + "`" + ` - Added include reference (non-destructive)

This pull request was generated by the [SLSA sourcetool](https://github.com/slsa-framework/source-tool) utility.
`
)

func getOIDCPipelineTemplate() string {
	return `# SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
# SPDX-License-Identifier: Apache-2.0
#
# SLSA Source Provenance Generation
# This job generates SLSA source provenance attestations and stores them in git notes

.slsa-source:
  stage: build
  image: golang:1.23
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  before_script:
    - git config user.name "GitLab CI"
    - git config user.email "ci@gitlab.com"
  script:
    - |
      # Install sourcetool
      go install github.com/slsa-framework/source-tool@latest

      # Generate provenance based on push type
      if [ -n "$CI_COMMIT_TAG" ]; then
        # Tag push
        sourcetool checktag \
          --commit $CI_COMMIT_SHA \
          --tag_name $CI_COMMIT_TAG \
          --output_signed_bundle bundle.intoto.jsonl
      else
        # Branch push
        sourcetool checklevelprov \
          --commit $CI_COMMIT_SHA \
          --branch $CI_COMMIT_REF_NAME \
          --output_signed_bundle bundle.intoto.jsonl
      fi

      # Store provenance in git notes
      git fetch origin "refs/notes/*:refs/notes/*" || true
      git notes append -F bundle.intoto.jsonl
      git push origin "refs/notes/*"
  artifacts:
    paths:
      - bundle.intoto.jsonl
    expire_in: 30 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
`
}

func getCosignPipelineTemplate() string {
	return `# SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
# SPDX-License-Identifier: Apache-2.0
#
# SLSA Source Provenance Generation (Cosign Signing)
# This job generates SLSA source provenance attestations and stores them in git notes

.slsa-source:
  stage: build
  image: golang:1.23
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  before_script:
    - git config user.name "GitLab CI"
    - git config user.email "ci@gitlab.com"
    - |
      # Install cosign
      COSIGN_VERSION=v2.2.1
      curl -LO "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64"
      chmod +x cosign-linux-amd64
      mv cosign-linux-amd64 /usr/local/bin/cosign
  script:
    - |
      # Install sourcetool
      go install github.com/slsa-framework/source-tool@latest

      # Export private key from CI variable to file
      echo "$COSIGN_PRIVATE_KEY" > cosign.key

      # Generate provenance
      if [ -n "$CI_COMMIT_TAG" ]; then
        sourcetool checktag \
          --commit $CI_COMMIT_SHA \
          --tag_name $CI_COMMIT_TAG \
          --output_unsigned_bundle bundle.intoto.jsonl
      else
        sourcetool checklevelprov \
          --commit $CI_COMMIT_SHA \
          --branch $CI_COMMIT_REF_NAME \
          --output_unsigned_bundle bundle.intoto.jsonl
      fi

      # Sign with cosign
      cosign sign-blob --key cosign.key \
        --output-signature bundle.intoto.jsonl.sig \
        bundle.intoto.jsonl

      # Store provenance in git notes
      git fetch origin "refs/notes/*:refs/notes/*" || true
      git notes append -F bundle.intoto.jsonl
      git push origin "refs/notes/*"
  artifacts:
    paths:
      - bundle.intoto.jsonl
      - bundle.intoto.jsonl.sig
    expire_in: 30 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
`
}

func getGitLabCIInclude() string {
	return `
include:
  - local: '.gitlab/slsa-source.yml'

slsa-source-provenance:
  extends: .slsa-source
`
}
